
	
import { Employee } from './employees/employees';
 
export const EMPLOYEES: Employee[] = [
{ id: 1, name: 'Damini Patel', position: 'Teller', phone:'615-669-XXXX'},
{ id: 2, name: 'David Wells', position: 'Personal Banker 1', phone:'704-998-XXXX'},
{ id: 3, name: 'Franklyn Reyes Varela', position: 'Teller', phone:'704-249-XXXX'},
{ id: 4, name: 'Jharna Whitehurst', position: 'Teller', phone:'252-414-XXXX'},
{ id: 5, name: 'Lennart Bendfeldt', position: 'Branch Manager aka "The Boss"', phone:'704-900-XXXX'},
{ id: 6, name: 'Marquis Blocker', position: 'Teller', phone:'704-904-XXXX'},
{ id: 7, name: 'Shanta Dutta', position: 'Teller', phone:'704-492-XXXX'},
{ id: 8, name: 'Sravanthi Rajavaram', position: 'Personal Banker 2', phone:'913-832-XXXX'},
{ id: 9, name: 'Victor Vo', position: 'Personal Banker 2', phone:'281-222-XXXX'},
{ id: 10, name: 'Wiynter Rodriguez', position: 'Teller', phone:'678-521-XXXX'},
{ id: 11, name: 'Deepshikha Sharma', position: 'Personal Banker 1', phone:'747-600-XXXX'},
{ id: 12, name: 'Echu Seifu', position: 'Teller', phone:'703-462-XXXX'},
{ id: 13, name: 'Erin Woodard', position: 'Lead Teller', phone:'919-454-XXXX'},
{ id: 14, name: 'Phillip Revak', position: 'Teller', phone:'919-621-XXXX'},
{ id: 15, name: 'Ibtxhis Khang', position: 'Teller', phone:'828-228-XXXX'},
{ id: 16, name: 'Kaleb Hill', position: 'Personal Banker 2 (Licensed)', phone:'828-541-XXXX'},
{ id: 17, name: 'Marcus Harris', position: 'Teller', phone:'980-319-XXXX'},
{ id: 18, name: 'Laura Aleman', position: 'Personal Banker 1', phone:'336-493-XXXX'},
{ id: 19, name: 'Lydia Oshunkentan', position: 'Security', phone:'205-239-XXXX'},
{ id: 20, name: 'Markus Harrison', position: 'Teller', phone:'704-785-XXXX'},
{ id: 21, name: 'Nick Harrison', position: 'Persoanl Banker 1', phone:'980-355-XXXX'},
{ id: 22, name: 'Sophie Cam', position: 'Service Manager', phone:'203-550-XXXX'},
{ id: 23, name: 'Brice Lewis', position: 'Customer Service Sales Rep', phone:'225-900-XXXX'},
{ id: 24, name: 'Chris Thao', position: 'Custodian', phone:'910-691-XXXX'},
{ id: 25, name: 'Geterry Sidbury-Crawford', position: 'Personal Banker 1', phone:'910-547-XXXX'},
{ id: 26, name: 'Kate Mejaski', position: 'Teller', phone:'317-702-XXXX'},
{ id: 27, name: 'Diana Flores', position: 'Customer Service Sales Rep', phone:'704-451-XXXX'},
{ id: 28, name: 'JSonya Watkins', position: 'Personal Banker 1', phone:'828-638-XXXX'},
{ id: 29, name: 'April Craig', position: 'Personal Banker 2 (Licensed)', phone:'980-202-XXXX'},
{ id: 30, name: 'Isaac Mendez', position: 'Teller', phone:'980-339-XXXX'},
{ id: 31, name: 'Julian Grant', position: 'Teller', phone:'704-713-XXXX'},
{ id: 31, name: 'Lee Dennis', position: 'Personal Banker 2 (Licensed)', phone:'828-308-XXXX'},
{ id: 31, name: 'Anubhuti Shivhare', position: 'Personal Banker 1', phone:'980-221-XXXX'},
{ id: 31, name: 'Hajar Alhassan', position: 'Personal Banker 2 (Licensed)', phone:'309-530-XXXX'},
{ id: 31, name: 'Shweta Deshmukh', position: 'Teller', phone:'440-715-XXXX'}
];
